language: bash

env:
  - SHUNIT_COLOR='always'

script:
  - ./shunit2_test.sh

  - shellcheck gen_test_results.sh shunit2 shunit2_test_*.sh
  - shellcheck -s sh shunit2_test_helpers

addons:
  apt:
    packages:
      - ksh
      - zsh
